/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package authPages;

import game.ÖmerYasirÖnal_StartPage;

import javax.swing.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author omeryasironal
 */
public class ÖmerYasirÖnal_LoginPage extends javax.swing.JFrame {

    public ÖmerYasirÖnal_LoginPage() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLocation(new java.awt.Point(400, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMail_2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLoginKayıtOl = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnGirişYap = new javax.swing.JButton();
        txtMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSifre_2 = new javax.swing.JPasswordField();
        txtSifre = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(435, 406));
        setPreferredSize(new java.awt.Dimension(435, 406));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Giriş Ekranı"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Mail Adresi:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Şifre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 65, 20));

        txtMail_2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(txtMail_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nadeem", 1, 18)); // NOI18N
        jLabel3.setText("1. Kullanıcı");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 20));

        btnLoginKayıtOl.setBackground(new java.awt.Color(102, 255, 0));
        btnLoginKayıtOl.setForeground(new java.awt.Color(0, 0, 255));
        btnLoginKayıtOl.setText("Kayıt Ol");
        btnLoginKayıtOl.setPreferredSize(new java.awt.Dimension(100, 23));
        btnLoginKayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginKayıtOlActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginKayıtOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 430, 10));

        btnGirişYap.setBackground(new java.awt.Color(102, 255, 0));
        btnGirişYap.setForeground(new java.awt.Color(0, 0, 255));
        btnGirişYap.setText("Giriş Yap");
        btnGirişYap.setPreferredSize(new java.awt.Dimension(100, 23));
        btnGirişYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirişYapActionPerformed(evt);
            }
        });
        jPanel1.add(btnGirişYap, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        txtMail.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Mail Adresi:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Şifre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 65, 20));

        txtSifre_2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(txtSifre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        txtSifre.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(txtSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Nadeem", 1, 18)); // NOI18N
        jLabel4.setText("2. Kullanıcı");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 400));

        pack();
    }//GEN-END:initComponents

    private void btnLoginKayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginKayıtOlActionPerformed
        ÖmerYasirÖnal_SingupPage sp = new ÖmerYasirÖnal_SingupPage();
        sp.setVisible(true); //Kayıt ekranı açılır.
    }//GEN-LAST:event_btnLoginKayıtOlActionPerformed

    /**
     * Bu method, kullanıcın girmiş olduğu email ve şifre değerlerini kontrol
     * eder. Eğer kullanıcı uygulamaya kayıtlı ise uygulamaya giriş yapar ve
     * başlangıç ekranına yönlendirilir. Kayıtlı değil ise "Kayıt ol" buttonuna
     * tıklayarak kayıt ekranına gider.
     */
    private void btnGirişYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirişYapActionPerformed

        String mail1 = txtMail.getText();
        String password1 = new String(txtSifre.getPassword());
        String mail2 = txtMail_2.getText();
        String password2 = new String(txtSifre_2.getPassword());
        boolean found1 = login(mail1, password1);
        boolean found2 = login(mail2, password2);

        if (mail1.isEmpty() || password1.isEmpty() || mail2.isEmpty() || password2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Boş alan bırakmayınız!", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else if (mail1.equals(mail2) && found1 && found2) {
            JOptionPane.showMessageDialog(null, "İki kullanıcı aynı olamaz", "Hata", JOptionPane.INFORMATION_MESSAGE);
        } else if (found1 && found2) {
            JOptionPane.showMessageDialog(null, "Giriş başarılı!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            ÖmerYasirÖnal_StartPage startPage = new ÖmerYasirÖnal_StartPage(mail1, mail2, this);
            txtMail.setText("");
            txtMail_2.setText("");
            txtSifre.setText("");
            txtSifre_2.setText("");
            startPage.setVisible(true);
        } else if (!found1) {
            JOptionPane.showMessageDialog(null, "1. Kullanıcının mail adresi veya şifresi hatalı!", "Hata", JOptionPane.ERROR_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "2. Kullanıcının mail adresi veya şifresi hatalı!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGirişYapActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGirişYap;
    private javax.swing.JButton btnLoginKayıtOl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMail_2;
    private javax.swing.JPasswordField txtSifre;
    private javax.swing.JPasswordField txtSifre_2;
    // End of variables declaration//GEN-END:variables

    /**
     * Bu method, kullanıcın bilgilerini kontrol ederek kayıtlı olup olmadığını
     * kontrol ederek girişin başarılı olup olmadığını kontrol eder.
     */
    public boolean login(String mail, String password) {

        boolean found;

        try {
            File file = new File("users.txt");
            try (Scanner scanner = new Scanner(file)) {
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    String[] parts = line.split(",");
                    if (parts.length >= 2) {
                        String fileMail = parts[0].trim();
                        String filePassword = parts[2].trim();
                        if (mail.equals(fileMail) && password.equals(filePassword)) {
                            found = true;
                            return found;

                        }
                    }
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return false;

    }
}
